language: r
cache: packages
sudo: required
warnings_are_errors: false

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install -y gdal netcdf-bin libproj-dev libudunits2-dev