language: r
cache: packages
sudo: required
warnings_are_errors: false
r_build_args: "--no-build-vignettes"
r_check_args: "--no-vignettes"

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install -y gdal-bin libgdal-dev libgdal20 netcdf-bin libproj-dev libudunits2-dev
